app <- ShinyDriver$new("../../")
app$snapshotInit("single_ems_no_data")

app$setInputs(ems_ids = "1401057")
app$setInputs(date_range = c("1900-01-01", "2016-01-01"))
app$setInputs(get_data = "click")
app$snapshot()
app$setInputs(box = "Results")
app$snapshot()
app$setInputs(box = "Plots")
app$snapshot()
app$setInputs(box = "About")
app$snapshot()